# Generated by Django 4.2.7 on 2023-11-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='articles',
            new_name='article',
        ),
    ]
