# Generated by Django 4.2.7 on 2023-12-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_articles_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', height_field=700, upload_to='articles/images', width_field=350),
        ),
    ]
